[build-system]
requires = [ "poetry-core>=1.8.0", "poetry-dynamic-versioning>1.0.0,<2.0.0" ]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[tool.poetry]
name = "sherlock-project"
version = "0.0.0"
description = "Hunt down social media accounts by username across social networks"
license = "MIT"
authors = [
    "Siddharth Dushantha"
]
maintainers = [
    "Paul Pfeister",
    "Matheus Felipe",
    "Sondre Karlsen Dyrnes"
]
readme = "docs/pyproj/README.md"
packages = [ { include = "sherlock"} ]
keywords = [ "osint", "reconnaissance", "information gathering" ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Security"
]


[tool.poetry.urls]
Homepage = "http://sherlock-project.github.io/"
Repository = "https://github.com/sherlock-project/sherlock.git"
Issues = "https://github.com/sherlock-project/sherlock/issues"

[tool.poetry.dependencies]
python = "^3.8"
certifi = "^2019.6.16"
colorama = "^0.4.1"
PySocks = "^1.7.0"
requests = "^2.22.0"
requests-futures = "^1.0.0"
stem = "^1.8.0"
torrequest = "^0.1.0"
pandas = ">1.0.0"
openpyxl = "^3.0.10"
exrex = "^0.11.0"

[tool.poetry.scripts]
sherlock = 'sherlock.sherlock:main'
