[build-system]
requires = [ "poetry-core>=1.6.0", "poetry-dynamic-versioning>1.0.0,<2.0.0" ]
build-backend = "poetry_dynamic_versioning.backend"
# poetry-core 1.8 not available in .fc39. Can upgrade to 1.8.0 at .fc39 EOL

[tool.poetry-dynamic-versioning]
enable = false
metadata = false
strict = true
vcs = "git"
# Matched tags:
# v0.0.0  followed by optional  -rc0 (release candidate)  OR  -b0 (public beta)
pattern = "^v(?P<base>\\d+(?:\\.\\d+){2})(?:-(?P<stage>(?:rc|b)\\d+?))??$"

[tool.poetry-dynamic-versioning.substitution]
folders = [ { path = "sherlock" } ]

[tool.poetry]
name = "sherlock-project"
version = "0.14.4"
description = "Hunt down social media accounts by username across social networks"
license = "MIT"
authors = [
    "Siddharth Dushantha"
]
maintainers = [
    "Paul Pfeister",
    "Matheus Felipe",
    "Sondre Karlsen Dyrnes"
]
readme = "docs/pyproj/README.md"
packages = [ { include = "sherlock"} ]
keywords = [ "osint", "reconnaissance", "information gathering" ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Security"
]
homepage = "http://sherlock-project.github.io/"
repository = "https://github.com/sherlock-project/sherlock.git"


[tool.poetry.urls]
"Bug Reporting" = "https://github.com/sherlock-project/sherlock/issues"
"Contributors" = "https://github.com/sherlock-project/sherlock/graphs/contributors"

[tool.poetry.dependencies]
python = "^3.8"
certifi = ">2019.6.16"
colorama = "^0.4.1"
PySocks = "^1.7.0"
requests = "^2.22.0"
requests-futures = "^1.0.0"
stem = "^1.8.0"
torrequest = "^0.1.0"
pandas = ">1.0.0"
openpyxl = "^3.0.10"
exrex = "^0.11.0"

[tool.poetry.scripts]
sherlock = 'sherlock.sherlock:main'
