name: Bug report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Thoughtfully filled out reports with detailed steps to reproduce are much more likely to be fixed.
        We can't fix what we can't reproduce!
  - type: dropdown
    id: package
    attributes:
      label: Installation method
      description: Which package are you using?
      options:
        - PyPI (via pip)
        - Homebrew
        - Docker
        - Kali repository (via apt)
        - Built from source
        - Other (indicate below)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you are experiencing
      placeholder: |
        When doing {action}, {expected result} is what I expected to happen, but {actual result} happened instead.
        This is undesirable because {reason}.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Write a step by step list that will allow us to reproduce this bug
      placeholder: |
        1. Do something
        2. Then do something else
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: If you have some additional information, please write it here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/sherlock-project/sherlock/blob/master/docs/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
